DATASET:
  TEST_NAME: california_housing_test.csv
  TRAIN_NAME: california_housing_train.csv
MODEL:
  HYPER_PARAMETERS:
    H1: 100
    H2: 20
    IN_FEATURES: 8
SOLVER:
  BATCH_SIZE: 500
  DEVICE: cpu
  LR: 0.0001
  METHOD: mlp-method
  OPTIMIZER_TYPE: adam
