DATASET:
  TRAIN_NAME: 'data/california_housing_train.csv'
  TEST_NAME: 'data/california_housing_test.csv'

SOLVER:
  LR: 0.00001
  OPTIMIZER_TYPE: 'adam'
  DEVICE: 'cpu'
  METHOD: 'mlp-method'
  BATCH_SIZE: 500

MODEL:
  HYPER_PARAMETERS:
    IN_FEATURES: 8
    H1: 100
    H2: 10