DATASET:
  TRAIN_NAME: 'california_housing_train.csv'
  TEST_NAME: 'california_housing_test.csv'

SOLVER:
  LR:
    MLM_BRANCH_1: 0.001
    MLM_BRANCH_2: 0.0001
    MLM_BRANCH_3: 0.00001
  OPTIMIZER_TYPE: 'adam'
  DEVICE: 'cpu'
  METHOD: 'mlp-method'
  BATCH_SIZE: 500

MODEL:
  HYPER_PARAMETERS:
    IN_FEATURES: 8
    H1:
      MLM_BRANCH_1: 100
      MLM_BRANCH_2: 200
    H2:
      MLM_BRANCH_1: 10
      MLM_BRANCH_2: 20